# Generated by Django 5.0.2 on 2024-02-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='menu.menu'),
        ),
    ]
