# Generated by Django 5.0.2 on 2024-02-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_title_alter_section_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('title',)},
        ),
    ]
